Document: autodeploy-agent
Title: Debian autodeploy-agent Manual
Author: <insert document author here>
Abstract: This manual describes what autodeploy-agent is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/autodeploy-agent/autodeploy-agent.sgml.gz

Format: postscript
Files: /usr/share/doc/autodeploy-agent/autodeploy-agent.ps.gz

Format: text
Files: /usr/share/doc/autodeploy-agent/autodeploy-agent.text.gz

Format: HTML
Index: /usr/share/doc/autodeploy-agent/html/index.html
Files: /usr/share/doc/autodeploy-agent/html/*.html


